---
- hosts: 172.31.47.246
  become: yes
  tasks:
  - name: execute linux command
    command:
      cmd: hostname -f
    register: myresult

  - name: display myresult
    debug:
      msg: "{{myresult}}"  